### ISSUE TITLE
Vivaldi install problem

### ISSUE THREAD

**Issue by ghost** [KaOS-Community-Packages/vivaldi#1]
0curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Error Vivaldi-snapshot_1.0.98.2-1_amd64.deb downloading
    Discontinuance...
exit status 1

**Comment by bvaudour** [comment]
Confirmed. I've no idea where it is, now.
There should be a new snapshot in 3 days (one snapshot each week), so PKGBUILD will be updated at this occasion. Just be patient.

**Comment by ghost** [comment]
Thank you!

**Comment by felipeacsi** [comment]
@KardiWeb Now it should be ok. There was a small change in the url ("v" instead of "V").

**Comment by ghost** [comment]
Thanks @felipeacsi

**Comment by felipeacsi** [comment]
You're welcome.
