### ISSUE TITLE
Vivaldi, slow updates

### ISSUE THREAD

**Issue by loopset** [KaOS-Community-Packages/vivaldi#2]
This browser is amazing, but, every time that it have a new version and I upgrade it, the process take so much time, because the speed of the download is very slow. Other packages download with more speed, but this take around 20 minutes, while a package with the same size (40mb) doesn't take more than 4-5 minutes. Does anyone know what it is? Thanks

**Comment by bvaudour** [comment]
No issue here.
But you can test the other mirror: at question "Do you want to edit the PKGBUILD?", reply "Yes", comment the line 12 and uncomment the line 13.

**Comment by loopset** [comment]
Thanks for your reply! I will try the next time! You are doing a great job maintaining this package. One more question, why can't I see videos on HD? When I go to youtube/html5, the options H.264 and MSE are in red.

**Comment by bvaudour** [comment]
H.264 codec is a non-free codec and Vivaldi team didn't pay to distribute it. The codec shipped with Chromium can be used, though:
https://gist.github.com/ruario/bec42d156d30affef655

**Comment by loopset** [comment]
Tkanks!
