### ISSUE TITLE
plasma-browser-integration not working

### ISSUE THREAD

**Issue by jomada** [KaOS-Community-Packages/vivaldi#4]
Plasma-browser-integration currently does not work in vivaldi, this may be the solution?
https://forum.kaosx.us/d/2177-plasma-browser-integration-not-working/2

**Comment by demmm** [comment]
If you are on the [build] repo, update and see if rebuild plasma-browser-integration (version 5.13.90-2) fixes.

**Comment by jomada** [comment]
Yes, I am in build, update and it was solved, thank you very much
